spring:
  profiles:
    active: local
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 5
      pool-name: HikariCP-POOL
      max-lifetime: 180000
      connection-timeout: 30000
  jpa:
    hibernate:
      connection:
        provider_class: org.hibernate.hikaricp.internal.HikariCPConnectionProvider
    properties:
      hibernate:
        default_schema: public
        show_sql: false
        format_sql: true
        use_sql: true
        hbm2ddl.auto: update
        dialect: org.hibernate.dialect.PostgreSQLDialect
        enable_lazy_load_no_trans: true
        use_sql_comments: true
        jdbc:
          lob:
            non_contextual_creation: true
    devtools:
      restart:
        enabled: false
      livereload:
        enabled: true
    main:
      allow-bean-definition-overriding: true
  security:
    oauth2:
      client:
        registration:
          google:
            redirect-uri: http://localhost:8080/secure/login/oauth-google/callback
            client-id: 49125488226-omd7fa2inu9h54fk2607h89224u4rhrc.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile